import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend, DynaPuff } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexendDeca = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const jua = DynaPuff({
  variable: "--font-jua",
  subsets: ["latin"],
  weight: ["400"],
});

import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexendDeca.variable} ${jua.variable} antialiased`}
      >
        <Providers>
          <ClerkProvider
            appearance={{
              variables: {
                colorPrimary: "#d69a6b",
                colorText: "black",
              },
            }}
          >
            {children}
          </ClerkProvider>
        </Providers>
      </body>
    </html>
  );
}
